### ISSUE TITLE
Bug in example demo

### ISSUE THREAD

**Issue by Vishnuxx** [dflex-js/dflex#684] opened 2023-08-21 16:04 UTC
I encountered a bug while testing the live demo of this library. The bug occurs when a list item is dragged and dropped exactly at the top of other list item in a specific manner. It seems like the dflex is creating additional unknown nodes to the list. Screenshots:
<img width="1306" alt="Screenshot 2023-08-21 at 8 56 32 PM" src="https://github.com/dflex-js/dflex/assets/74808440/09d30af7-03ae-4ea5-8626-d0e087e9313d">
<img width="1680" alt="Screenshot 2023-08-21 at 8 57 15 PM" src="https://github.com/dflex-js/dflex/assets/74808440/3ab1ed83-64ff-4d30-abab-f0e6490f7bf1">
<img width="1680" alt="Screenshot 2023-08-21 at 9 29 58 PM" src="https://github.com/dflex-js/dflex/assets/74808440/55834fde-1dac-4523-932d-6eea93170b3b">

**Comment by jalal246** [comment] 2023-08-25 09:41
@Vishnuxx Sorry to hear that you encountered a bug in the DFlex live demo. The screenshot you provided is very clear and does indicate a bug. However, I was unable to reproduce the bug myself.

DFlex does not change the DOM or mutate it. Instead, it reconciles when the drag ends.

There is an issue with Next.js server-side rendering when the store is handling multiple layouts across multiple routing pages. This is why I have reduced the demos to just two. To work around this issue, I should install the Next.js app and test DFlex there as an extra step to make sure that everything is working correctly. However, as Next.js is rapidly moving towards the app directory, I am not sure if I should continue this type of effort in this direction.

I will continue to investigate this bug and try to reproduce it. If I am able to do so, I will fix it and release a new version of DFlex.

**Comment by jalal246** [comment] 2023-11-04 22:06
Hi @Vishnuxx,  This issue appears to be resolved based on fixes in previous PRs #639, #715, #722, #734. The behavior described here is no longer happening. Please verify on your end, but likely this can be closed out now.

**Closed by jalal246** 2023-11-04 22:06 UTC
